services:
  api:
    build: .
    command: uvicorn python.fastApi.PokeAPI:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - path: .env
        required: false

  streamlit:
    build: .
    command: streamlit run python/streamlit/pokedex.py --server.port 8501 --server.address 0.0.0.0
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    environment:
      - FAST_API_URL=http://api:8000
    env_file:
      - path: .env
        required: false
    depends_on:
      - api